version: '3.8'
services:

  app:
    build: .
    container_name: app
    image: app
    environment:
      PG_URL: 'postgres://user:password@postgres:5432/app'
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'app'
    ports:
      - "5432:5432"

volumes:
  pg-data: